### ISSUE TITLE
AAD login redirects to https://my.sonarqube.url/sessions/new?return_to=............(etc) without displaying Microsoft login page

### ISSUE THREAD

**Issue by seguemark** [hkamel/sonar-auth-aad#132]
I'm never getting sent to the Microsoft login page.  Instead, it redirects to https://my.sonarqube.url/sessions/new?return_to=............(etc) 

I am using a reverse proxy with IIS to enable SSL support, and I have followed the troubleshooting instructions for this (unchecked 'Reverse rewrite host in response headers') and the problem still occurs.

**Comment by srvrguy** [comment]
Hi, I'm checking if you still need assistance.

I don't normally run SQ with IIS, so please provide some details on your configuration so I can try to duplicate it and attempt to reproduce your issue.

**Comment by zshulman2** [comment]
I am getting basically the same issue.  I followed the [IIS Reverse Proxy Guide](https://jessehouwing.net/sonarqube-configure-ssl-on-windows/) and then per the troubleshooting [here](https://github.com/hkamel/sonar-auth-aad/wiki/Troubleshooting) I disabled Reverse rewrite host.  

After authentication I get the AAD error below

AADSTS50011: The redirect URI 'http://mysonarqubeurl:9000/oauth2/callback/aad' specified in the request does not match the redirect URIs configured for the application 'AAD CLIENT ID'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

Tried changing the Redirect URL of the AAD app but then it redirects to a page does not exist error instead of the above one

**Comment by srvrguy** [comment]
That AADSTS error you're seeing basically means that the URL SonarQube is passing for the redirect back is not on the registered list for your AAD application registration. You'd need to add that URL to the list on the AAD application registration side. Be aware that you cannot use HTTP urls for anything beside "localhost". All redirect URLs _must_ be HTTPS. This is a security restriction on the Microsoft side.

**Comment by srvrguy** [comment]
This issue is old and hasn't had any activity. If the problem still exists, please open a new issue.
