### ISSUE TITLE
 Is version 1.3.2 compatible with sonarqube 8.9.1

### ISSUE THREAD

**Issue by thinksabin** [hkamel/sonar-auth-aad#155]
hi there,

Apologies, I couldnt find any clear information about compatibility.

We are using sonarqube 8.9.1 and wondering if version 1.3.2 (Updates commons-text to fix https://github.com/advisories/GHSA-599f-7c49-w659.) release supports it.

Can the security issue with commons-text be exploited through this plugin?

Thanks

**Comment by srvrguy** [comment]
I don't recommend using version 1 of the plugin anymore, it's using deprecated libraries and login methods with MS. I'm not sure if it will work with SonarQube 8.9, but I don't believe there are any explicit incompatibilities. If 1.3.1 works, then 1.3.2 should as well since the only change was to update the commons-text library.

The vulnerability in commons-text shouldn't be a problem. The library is only used in the group sync feature, and as far as I could tell when investigating, the function used there wasn't affected by the vulnerability. It would also only be an issue if there was a maliciously-named group that could be returned during the sync. Basically, the exploitability of the issue was extremely low.
