### ISSUE TITLE
Allow different email for user account

### ISSUE THREAD

**Issue by MattVSTS** [hkamel/sonar-auth-aad#3]
As a SonarQube administrator I would like to be able to use a different email when the user is backed by Azure Active Directory.
At the moment this isn't possible because the Alternate Email from AAD isn't retrived and the SonarQube 'Email' field for the user is overwritten every time a user logs in.

**Comment by hkamel** [comment]
Hello @MattVSTS thanks a lot for the feedback, I'm working on this and shall update you soon whether this is possible or not.

**Comment by hkamel** [comment]
This issue still pending as we need Sonarqube to support such scenario, please check https://jira.sonarsource.com/browse/SONAR-7218

**Comment by joerocklin** [comment]
@hkamel the referenced issue has been marked as resolved. We're considering using this plugin but would need to handle alternate emails. Does anything else have to change with this plugin to support that?

**Comment by srvrguy** [comment]
The issue was closed as a duplicate and the linked issue still shows as open. I see on SQ8 there is an option for an admin to manually add additional SCM names. This doesn't quite match with the original request, which was to use the "alternative email" field in AAD, but perhaps the solution would be to add the alternative e-mail to the SCM account for the user, if that data exists.
