### ISSUE TITLE
Migrating issue from Gitlab auth plugin

### ISSUE THREAD

**Issue by Kemyke** [hkamel/sonar-auth-aad#77]
First of all, thanks for the plugin. 

Currently we are using Gitlab sonar auth plugin to authenticate our users. We would like to switch to you plugin to use our Azure AD. The problem is that the email addresses are the same in both system.
So when i configure the plugin, the below error is shown for already existing users:
![image](https://user-images.githubusercontent.com/5611190/64031371-8c185700-cb48-11e9-82d1-cce790397bc6.png)
And in the log there is a line:
`ERROR web[AWziv9fGUZ/OYGa0AAJn][o.a.a.a.AadIdentityProvider] Exception:org.sonar.server.authentication.exception.EmailAlreadyExistsRedirectionException`

We are able to login through Azure AD plugin if the user is brand new and has never logged through Gitlab plugin.

What is the preferred way to switch between auth plugins? If i deactivate the existing users will it solve this problem?

**Comment by srvrguy** [comment]
The easiest way to "switch" is to set the "Login generation strategy" to "Unique". It should be that by default, actually. This will create new users with a non-overlapping username which should resolve the main issue. Unfortunately, this also breaks assignments and history since they are treated as separate users.

If that doesn't resolve your problem or if you want to keep the user accounts the same on the SQ side, feel free to reply back and we can go over other options or fixes.

**Comment by hameno** [comment]
We need this aswell, we want to switch from old internal LDAP to MS AD. It would be even better, if the two could work simultaniously.

**Comment by srvrguy** [comment]
As far as I can tell, there is no way to have multiple identity providers for a single user. The system is just not designed that way. As for having this plugin do any kind of "migration", I'm just not sure how good of an idea that is. We don't want to clobber a working user, and the only supported way of doing this is via the SQ Web API, as noted above.

Starting in SQ 8.7, there's a specific endpoint to update the identity provider for a user (api/isers/update_identity_provider) in addition to the existing user update API endpoint (api/users/update).

I honestly think this issue is outside the scope of this plugin unless someone has a really good argument for why it is.
