### ISSUE TITLE
Token is not removed automatically

### ISSUE THREAD

**Issue by tomizius** [hkamel/sonar-auth-aad#89]
If you create a user in the azure active directory and log in with it in sonarqube it works.

The Problem is, if you grant admin privileges and create a access token, the token is usable after the user is removed out of the azure active directory.

Is there any way to fix this? The token needs to be deactived when the user is removed out of the azure active directory.

**Comment by srvrguy** [comment]
As far as I am aware, there isn't really a good way to do this. The login method is pull only, and while the plugin supports using Azure AD as a place to validate a user login, SonarQube doesn't rely on that source for all identity information, including access tokens. As you have seen, access tokens bypass the whole Azure login process.

As that is the case, there is no way with the plugin itself to remove a user that is no longer in AAD, and I'm honestly not sure it's even in scope for this plugin to do that.

I'm going to close this as a "wontfix" for that reason. Feel free to respond if you have a good counter-argument, but keep in mind that even if I agree that something _should_ be done, it's not likely to be incorporated directly in this plugin due to the limitations of what we can do.
