### ISSUE TITLE
Group sync is too brute force

### ISSUE THREAD

**Issue by downstevedown** [hkamel/sonar-auth-aad#96]
So, I'd like my Azure AD user to be part of the Administrators group. Great. Added it to sonar-administrators. Turned on Group Sync. Every time I log in, I see that my user only exists in the sonar-users group. When I look in the web log in DEBUG mode, I see it removing my user from the local sonar groups.

If I turn off Group Sync, this doesn't happen. I remain in sonar-administrators. Ideally, I'd like to have Azure Group Sync sync only groups that it matches, and not mess with groups that don't.

**Comment by srvrguy** [comment]
The problem with your suggestion is that removing any user from a group in AD that exists in SQ won't be reflected. Say, for example, you temporarily gave a user elevated access by adding them to a security group. By only adding groups and never removing in SQ, that user now potentially has elevated access in SQ that they shouldn't have, and you have to manually manage things.

The better solution is to make a group called "Administrators" in SQ and give it the same global permissions as the sonar-administrators group. You can do this by going to "Administration -> Security -> Global Permissions" and "Administration -> Security -> Permission Templates".

The sonar-users group is special in that all users are members by default. That's why your user is in it, even with group sync enabled.

**Comment by srvrguy** [comment]
An alternate solution is to create an AD group named "sonar-administrators" and add what groups and/or users you want to be there on SonarQube. They should then sync to that built-in group correctly.

**Comment by thomasminney** [comment]
@srvrguy can user removal via Azure AD group sync be possible if SQ groups can be marked as either manual or azure-linked? This could be done under the Azure AD plugin settings UI in SQ where SQ-group to Azure group matching can be listed.

**Comment by srvrguy** [comment]
@thomasminney Not sure I fully understand your request, so I'll try to address what I think you're talking about.

If you're talking about having some kind of manual AAD to SQ group mapping, it might be possible, but would be tricky. The code basically takes the groups that the user is in and adds them to the SQ user profile on sign-in. This list _replaces_ any existing membership for that user. The benefit is that removing a user from a group in AAD means the user is removed from the SQ group on their next login. SQ doesn't have any kind of fancy metadata for groups, just the name and a description.

If we wanted to do some kind of "manual" linking, we'd need to have some kind of custom setting UI where the admin can type in the mappings. Then the process would be that when the user logs in and the code gets the group memberships, it would need to apply any name transforms (take a matching AAD group name, change it to the listed SQ group name) and then update the user profile before logging in the user.

Honestly, I'm not sure that the benefit of such a system would outweigh the complexity being added to the plugin. This is especially complex when you have to troubleshoot why a mapping doesn't work, or why mappings suddenly broke completely after making a change. I'm also not sure how many people using this login method would have issues with creating SQ groups with names mirroring that which they're using in AAD.

Going back to the original problem this issue was created for, the only mapping issue was with the sonar-administrators group. This can be "solved" with the options I gave in my prior response.

**Comment by thomasminney** [comment]
@srvrguy Yes a custom setting is what I was thinking. It would allow flexibility between choosing with groups are manual within SonarQube and which can be controlled by AAD.

Thank you for the reasons why the group sync works this way. We will review the group setup we were planning to implement in order to use AAD group sync.
